In [1]:
%pip install numpy

import numpy as np

# word embeddings (fake)
words = ["I", "love", "data"]
embeddings = np.array([
    [1, 0, 1],   # I
    [1, 1, 0],   # love
    [0, 1, 1]    # data
])

# Query, Key, Value = same (self-attention)
Q = embeddings
K = embeddings
V = embeddings

# Attention scores
scores = Q @ K.T

# Softmax
def softmax(x):
    e = np.exp(x - np.max(x))
    return e / e.sum(axis=1, keepdims=True)

weights = softmax(scores)

# Output
output = weights @ V

print("Attention Weights:\n", weights)
print("\nFinal Representations:\n", output)


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 3.2 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.
Attention Weights:
 [[0.57611688 0.21194156 0.21194156]
 [0.21194156 0.57611688 0.21194156]
 [0.21194156 0.21194156 0.57611688]]

Final Representations:
 [[0.78805844 0.42388312 0.78805844]
 [0.78805844 0.78805844 0.42388312]
 [0.42388312 0.78805844 0.78805844]]


In [2]:

%pip install seaborn matplotlib
import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(weights, annot=True, xticklabels=words, yticklabels=words)
plt.show()


  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 1.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.1 MB/s eta 0:00:00
  Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 4.3 MB/s eta 0:00:00
  Using cached kiwisolver-1.4.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.3 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 3.8 MB/s eta 0:00:0000:0100:01m
Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 3.7 MB/s eta 0:00:0000:0100:01
Using cached kiwisolver-1.4.9-cp31

In [ ]:
 [[0.57611688 0.21194156 0.21194156]
 [0.21194156 0.57611688 0.21194156]
 [0.21194156 0.21194156 0.57611688]]